project_id = "krupo-local"
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
[db]
port = 54322
major_version = 17
[auth]
enabled = true
site_url = "https://krupo-media-marketplace.krupo-media-marketplace.workers.dev"
additional_redirect_urls = [
  "https://krupo-media-marketplace.krupo-media-marketplace.workers.dev/auth/callback",
  "https://krupo-media-marketplace.krupo-media-marketplace.workers.dev/auth/email-callback",
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/auth/email-callback",
  "http://127.0.0.1:3000/auth/callback",
  "http://127.0.0.1:3000/auth/email-callback",
]
enable_signup = true
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "1m"
otp_length = 8
[auth.email.template.confirmation]
subject = "ยืนยันอีเมลสำหรับ KruPo คลังสื่อ"
content_path = "./supabase/templates/confirmation.html"
[auth.email.template.recovery]
subject = "ตั้งรหัสผ่านใหม่สำหรับ KruPo คลังสื่อ"
content_path = "./supabase/templates/recovery.html"
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
