// @ts-expect-error generated by `pnpm cf:build` before Wrangler bundles this entry.
import openNextWorker from "./.open-next/worker.js";
type WorkerContext={waitUntil(promise:Promise<unknown>):void;passThroughOnException():void};
type WorkerEnv=CloudflareEnv&{NEXT_PUBLIC_APP_URL:string};
const worker={fetch(request:Request,env:WorkerEnv,ctx:WorkerContext){return openNextWorker.fetch(request,env,ctx)},scheduled(_controller:unknown,env:WorkerEnv,ctx:WorkerContext){const request=new Request(new URL("/api/jobs/run",env.NEXT_PUBLIC_APP_URL),{method:"POST",headers:{Authorization:`Bearer ${env.JOB_RUNNER_SECRET}`,"x-krupo-scheduled":"cloudflare"}});ctx.waitUntil(openNextWorker.fetch(request,env,ctx).then((response:Response)=>{if(!response.ok)throw new Error(`scheduled job failed (${response.status})`)}))}};
export default worker;
