import type {Metadata} from "next";
import {CreatorNav} from "@/components/creator-nav";
export const metadata:Metadata={title:"เพิ่มสื่อใหม่",robots:{index:false,follow:false}};
const subjects=["คณิตศาสตร์","วิทยาศาสตร์","ภาษาไทย","ภาษาอังกฤษ","สังคมศึกษา","คอมพิวเตอร์","ศิลปะ","สุขศึกษา"];
const mediaTypes=["เกมการศึกษา","ใบงาน","แบบฝึกหัด","PowerPoint","PDF","แบบทดสอบ","วิดีโอ","แผนการสอน","อื่น ๆ"];
export default function Page(){return <div className="container-page py-9">
  <h1 className="text-3xl font-black text-[#0B2F6B]">เพิ่มสื่อใหม่</h1><p className="mt-2 text-[#66758A]">ไฟล์จะเข้า Temporary Review Area ก่อน ไม่ส่งเข้า permanent storage ทันที</p><div className="mt-6"><CreatorNav/></div>
  <form method="post" action="/api/creator/submissions" encType="multipart/form-data" className="soft-card mt-7 grid gap-5 p-7">
    <div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2 font-bold">ชื่อสื่อ<input required name="titleTh" className="field"/></label><label className="grid gap-2 font-bold">วิชา<select required name="subject" className="field">{subjects.map(x=><option key={x}>{x}</option>)}</select></label></div>
    <label className="grid gap-2 font-bold">รายละเอียด<textarea required name="descriptionTh" className="field min-h-32"/></label>
    <div className="grid gap-5 md:grid-cols-3"><label className="grid gap-2 font-bold">ระดับชั้น<select required name="grade" className="field"><option>อนุบาล</option>{Array.from({length:6},(_,i)=><option key={`p${i+1}`}>ประถมศึกษาปีที่ {i+1}</option>)}{Array.from({length:6},(_,i)=><option key={`m${i+1}`}>มัธยมศึกษาปีที่ {i+1}</option>)}<option>อาชีวศึกษา</option><option>อื่น ๆ</option></select></label><label className="grid gap-2 font-bold">ประเภท<select name="mediaType" className="field">{mediaTypes.map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 font-bold">ราคา (บาท)<input required name="priceBaht" type="number" min="0" step="1" className="field"/></label></div>
    <div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2 font-bold">Game URL<input name="gameUrl" type="url" className="field" placeholder="เก็บและอ่านเฉพาะฝั่ง Server"/></label><label className="grid gap-2 font-bold">Backup URL<input name="backupUrl" type="url" className="field"/></label></div>
    <div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2 font-bold">แพลตฟอร์มต้นทาง<select name="sourcePlatform" className="field">{["Wordwall","Genially","Canva","Google Sites","LearningApps","Other"].map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 font-bold">Verification Token<input name="verificationToken" className="field" placeholder="เช่น KRUPO-XXXX (ถ้ารองรับ)"/></label></div>
    <div className="grid gap-5 md:grid-cols-3"><label className="grid gap-2 font-bold">รูปปก<input name="cover" type="file" accept="image/png,image/jpeg,image/webp" className="field"/></label><label className="grid gap-2 font-bold">ไฟล์หลัก<input name="mediaFile" type="file" accept=".pdf,.pptx,.docx,.zip" className="field"/></label><label className="grid gap-2 font-bold">ไฟล์สำรอง<input name="backupFile" type="file" accept=".pdf,.pptx,.docx,.zip" className="field"/></label></div>
    <div className="rounded-xl bg-[#FFF8E6] p-4 text-sm text-[#7A5710]">Basic check ตรวจชนิดไฟล์ ลายเซ็นอันตราย hash และความซ้ำ แต่ไม่ใช่ malware scanner ไฟล์จะคงอยู่ใน quarantine จนผู้ตรวจบันทึกผล clean อย่างชัดเจน</div>
    <label className="grid gap-2 font-bold">Tags<input name="tags" className="field" placeholder="คณิตศาสตร์, ป.4, เกม"/></label><label className="grid gap-2 font-bold">Ownership Evidence<textarea required name="ownershipEvidence" className="field min-h-24" placeholder="อธิบายแหล่งที่มาและสิทธิ์ในผลงาน"/></label><label className="flex gap-3 text-sm"><input required type="checkbox" name="ownershipConfirmed"/>ฉันยืนยันว่าเป็นเจ้าของหรือมีสิทธิ์เพียงพอ</label><button className="btn btn-primary w-fit" type="submit">ส่งเข้าตรวจสอบ</button>
  </form>
</div>}
