import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, Gamepad2, Search, ShieldCheck, Sparkles } from "lucide-react";
import { MediaCard } from "@/components/media-card";
import { subjects } from "@/features/catalog/demo-media";
import { listPublishedMedia } from "@/server/repositories/catalog-repository";

export default async function HomePage(){const media=await listPublishedMedia({limit:6});return <>
  <section className="container-page pt-7"><div className="relative overflow-hidden rounded-[30px] border border-[#DDE9FA] bg-gradient-to-br from-[#F3F8FF] via-white to-[#EEEAFF] px-6 py-9 md:px-12 md:py-12"><div className="relative z-10 grid items-center gap-8 lg:grid-cols-[1.05fr_.95fr]"><div><span className="badge bg-white text-[#6554E8] shadow-sm"><Sparkles className="h-4 w-4"/>ตลาดสื่อสำหรับครูไทย</span><h1 className="mt-5 max-w-2xl text-4xl font-black leading-[1.18] tracking-tight text-[#0B2F6B] md:text-6xl">สื่อการสอนคุณภาพ<br/><span className="text-[#0F5BD8]">ที่ห้องเรียนจะสนุกขึ้น</span></h1><p className="mt-5 max-w-xl text-base leading-8 text-[#66758A] md:text-lg">ค้นหาเกมการศึกษา ใบงาน และบทเรียนจากผู้สร้างที่ใส่ใจ พร้อมระบบสิทธิ์และการตรวจสอบที่ออกแบบเพื่อครู</p><form action="/media" className="mt-7 flex max-w-xl gap-2 rounded-2xl bg-white p-2 shadow-xl shadow-blue-950/10"><label htmlFor="hero-search" className="sr-only">ค้นหาสื่อ</label><Search className="ml-2 mt-3 h-5 w-5 shrink-0 text-[#66758A]"/><input id="hero-search" name="q" className="min-w-0 flex-1 bg-transparent px-2 outline-none" placeholder="ค้นหาเกม ใบงาน หรือวิชา..."/><button className="btn btn-primary" type="submit">ค้นหา</button></form><div className="mt-6 flex flex-wrap gap-3"><Link className="btn btn-primary" href="/games"><Gamepad2 className="h-5 w-5"/>ดูเกมทั้งหมด</Link><Link className="btn btn-secondary" href="/media?price=free"><BookOpen className="h-5 w-5"/>สื่อฟรี</Link></div></div><Image src="/brand/hero-learning.svg" alt="แท็บเล็ต หนังสือ และอุปกรณ์การเรียนรู้" width={640} height={390} className="w-full" priority/></div></div></section>
  <section className="container-page py-14"><div className="flex items-end justify-between"><div><p className="font-bold text-[#0F5BD8]">ค้นหาง่าย ใช้ได้เร็ว</p><h2 className="section-title mt-1">เลือกตามรายวิชา</h2></div><Link href="/media" className="hidden items-center gap-1 font-semibold text-[#0F5BD8] sm:flex">ดูทั้งหมด <ArrowRight className="h-4 w-4"/></Link></div><div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{subjects.map((s,i)=><Link key={s} href={`/media?subject=${encodeURIComponent(s)}`} className="soft-card flex min-h-24 flex-col items-center justify-center gap-2 p-3 text-center font-bold text-[#0B2F6B] transition hover:-translate-y-1 hover:border-[#AAC9F6]"><span className="grid h-11 w-11 place-items-center rounded-2xl text-white" style={{background:["#3D8EF7","#2FC58D","#F39A43","#8B62E8","#24AAA8","#487EEA"][i]}}>{s.slice(0,1)}</span>{s}</Link>)}</div></section>
  <section className="bg-[#F7FAFF] py-14"><div className="container-page"><div className="flex items-end justify-between"><div><p className="font-bold text-[#2B9B70]">คัดสรรสำหรับห้องเรียน</p><h2 className="section-title mt-1">สื่อแนะนำ</h2></div><Link href="/media" className="flex items-center gap-1 font-semibold text-[#0F5BD8]">ดูทั้งหมด <ArrowRight className="h-4 w-4"/></Link></div>{media.length?<div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{media.map(m=><MediaCard media={m} key={m.id}/>)}</div>:<div className="soft-card mt-6 p-10 text-center text-[#66758A]">ยังไม่มีสื่อที่ผ่านการอนุมัติ</div>}</div></section>
  <section className="container-page py-14"><div className="grid gap-5 md:grid-cols-3">{[[ShieldCheck,"ปลอดภัยและตรวจสอบได้","สิทธิ์ผู้ใช้ ลิงก์ และการเปลี่ยนแปลงสำคัญมีประวัติย้อนหลัง"],[Sparkles,"สนับสนุนผู้สร้างไทย","ผู้สร้างได้รับส่วนแบ่ง 85–90% ตามระดับความน่าเชื่อถือ"],[Gamepad2,"Game Link First","เปิดเกมได้เร็ว พร้อมตรวจสุขภาพลิงก์และระบบสำรอง"]].map(([Icon,title,text])=><div className="soft-card p-6" key={title as string}><Icon className="h-9 w-9 text-[#0F5BD8]"/><h3 className="mt-4 text-lg font-extrabold text-[#0B2F6B]">{title as string}</h3><p className="mt-2 text-sm leading-6 text-[#66758A]">{text as string}</p></div>)}</div></section>
  </>}
