import type { StorageMetadata,StorageProvider,UploadInput } from "./storage-provider";

interface DriveConfig{clientId:string;clientSecret:string;refreshToken:string;rootFolderId:string;}
interface DriveFile{id:string;name:string;mimeType:string;size?:string;createdTime?:string;md5Checksum?:string;parents?:string[];appProperties?:Record<string,string>}
export class GoogleDriveStorageProvider implements StorageProvider{
 readonly name="google_drive" as const;private accessToken?:{value:string;expiresAt:number};constructor(private config:DriveConfig){}
 private async token(){if(this.accessToken&&this.accessToken.expiresAt>Date.now()+30000)return this.accessToken.value;const body=new URLSearchParams({client_id:this.config.clientId,client_secret:this.config.clientSecret,refresh_token:this.config.refreshToken,grant_type:"refresh_token"});const res=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!res.ok)throw new Error(`Google Drive authentication failed (${res.status})`);const data=await res.json() as {access_token:string;expires_in:number};this.accessToken={value:data.access_token,expiresAt:Date.now()+data.expires_in*1000};return data.access_token}
 private async request(url:string,init:RequestInit={}){const headers=new Headers(init.headers);headers.set("Authorization",`Bearer ${await this.token()}`);const res=await fetch(url,{...init,headers});if(!res.ok)throw new Error(`Google Drive request failed (${res.status})`);return res}
 private metadata(file:DriveFile,path:string):StorageMetadata{return {provider:this.name,fileId:file.id,path,fileName:file.name,mimeType:file.mimeType,size:Number(file.size??0),checksum:file.appProperties?.sha256??file.md5Checksum,createdAt:file.createdTime}}
 async upload(input:UploadInput){const boundary=`krupo_${crypto.randomUUID()}`;const meta={name:input.fileName,parents:[this.config.rootFolderId],appProperties:{path:input.path,sha256:input.checksum??""}};const blob=input.data instanceof Blob?input.data:new Blob([input.data as BlobPart],{type:input.mimeType});const body=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(meta)}\r\n--${boundary}\r\nContent-Type: ${input.mimeType}\r\n\r\n`,blob,`\r\n--${boundary}--`]);const res=await this.request("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,size,createdTime,md5Checksum,appProperties",{method:"POST",headers:{"Content-Type":`multipart/related; boundary=${boundary}`},body});return this.metadata(await res.json() as DriveFile,input.path)}
 async download(id:string){const res=await this.request(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?alt=media`);const headers=new Headers(res.headers);headers.set("Cache-Control","private, no-store");headers.set("Content-Disposition","attachment");return new Response(res.body,{status:res.status,headers})}
 async delete(id:string){await this.request(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}`,{method:"DELETE"})}
 async exists(id:string){try{await this.getMetadata(id);return true}catch{return false}}
 async getMetadata(id:string){const res=await this.request(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?fields=id,name,mimeType,size,createdTime,md5Checksum,appProperties`);const f=await res.json() as DriveFile;return this.metadata(f,f.appProperties?.path??"")}
 async move(id:string,path:string){const current=await this.getMetadata(id);const res=await this.request(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?fields=id,name,mimeType,size,createdTime,md5Checksum,appProperties`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({appProperties:{path,sha256:current.checksum??""}})});return this.metadata(await res.json() as DriveFile,path)}
 async copy(id:string,path:string){const source=await this.getMetadata(id);const res=await this.request(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}/copy?fields=id,name,mimeType,size,createdTime,md5Checksum,appProperties`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:source.fileName,parents:[this.config.rootFolderId],appProperties:{path,sha256:source.checksum??""}})});return this.metadata(await res.json() as DriveFile,path)}
 async health(){try{await this.request(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(this.config.rootFolderId)}?fields=id`);return {status:"healthy" as const,message:"เชื่อมต่อ Google Drive ได้"}}catch{return {status:"critical" as const,message:"เชื่อมต่อ Google Drive ไม่สำเร็จ"}}}
}
