import { sha256 } from "@/server/security/crypto";import type { CopyrightCheckResult,CopyrightRiskProvider,RiskEvidence } from "./copyright-risk-provider";
const now=()=>new Date().toISOString();
function normalized(text:string){return text.normalize("NFKC").toLocaleLowerCase("th").replace(/[^\p{L}\p{N}]+/gu,"").trim()}
function ngrams(value:string,n=3){const s=normalized(value);const out=new Set<string>();for(let i=0;i<=s.length-n;i++)out.add(s.slice(i,i+n));return out}
export function textSimilarity(a:string,b:string){const aa=ngrams(a),bb=ngrams(b);if(!aa.size&&!bb.size)return 1;let same=0;for(const x of aa)if(bb.has(x))same++;return (2*same)/(aa.size+bb.size)}
export function perceptualDHash(grayscale:number[],width:number,height:number){if(width<2||height<1||grayscale.length<width*height)throw new Error("ข้อมูล pixel ไม่ถูกต้อง");const rows=Math.min(height,8),cols=Math.min(width-1,8);let bits="";for(let y=0;y<rows;y++){const yy=Math.floor(y*height/rows);for(let x=0;x<cols;x++){const xx=Math.floor(x*(width-1)/cols);bits+=grayscale[yy*width+xx]>grayscale[yy*width+xx+1]?"1":"0"}}return BigInt(`0b${bits||"0"}`).toString(16).padStart(16,"0")}
export function hammingSimilarity(a:string,b:string){try{let x=BigInt(`0x${a}`)^BigInt(`0x${b}`),count=0;while(x){count+=Number(x&1n);x>>=1n}return 1-count/Math.max(a.length,b.length)/4}catch{return 0}}
function result(inputHash:string,risk:CopyrightCheckResult["risk"],reason:string,evidence:RiskEvidence[]=[],urlsFound:string[]=[]):CopyrightCheckResult{return {risk,provider:"BASIC",model:"deterministic-rules",modelVersion:"1.0.0",inputHash,checkedAt:now(),reason,evidence,urlsFound}}
export class BasicCopyrightChecker implements CopyrightRiskProvider{readonly name="BASIC";
 async checkText(input:Parameters<CopyrightRiskProvider["checkText"]>[0]){const hash=await sha256(normalized(input.text));const matches=(input.knownTexts??[]).map(x=>({id:x.id,similarity:textSimilarity(input.text,x.text)})).filter(x=>x.similarity>=.55).sort((a,b)=>b.similarity-a.similarity);const top=matches[0];return result(hash,!top?"LOW":top.similarity>=.9?"HIGH":"MEDIUM",!top?"ไม่พบข้อความคล้ายในคลัง KruPo":`พบข้อความคล้าย ${Math.round(top.similarity*100)}%`,matches.map(x=>({kind:"text_similarity",reference:x.id,similarity:x.similarity,detail:"เทียบอักษรแบบ normalized trigram"}))) }
 async checkImage(input:Parameters<CopyrightRiskProvider["checkImage"]>[0]){const hash=await sha256(input.bytes);if(!input.grayscalePixels||!input.width||!input.height)return result(hash,"UNKNOWN","ยังไม่มี image decoder สำหรับ perceptual hash; ส่งให้ผู้ตรวจ",[{kind:"sha256",detail:hash}]);const phash=perceptualDHash(input.grayscalePixels,input.width,input.height);const matches=(input.knownHashes??[]).map(x=>({id:x.id,similarity:hammingSimilarity(phash,x.hash)})).filter(x=>x.similarity>=.85);return result(hash,matches.some(x=>x.similarity>=.96)?"HIGH":matches.length?"MEDIUM":"LOW",matches.length?"พบภาพที่ perceptual hash ใกล้เคียง":"ไม่พบภาพใกล้เคียง",[{kind:"perceptual_hash",detail:phash},...matches.map(x=>({kind:"image_similarity",reference:x.id,similarity:x.similarity,detail:"dHash comparison"}))])}
 async checkFile(input:Parameters<CopyrightRiskProvider["checkFile"]>[0]){const hash=await sha256(input.bytes);const matches=(input.knownChecksums??[]).filter(x=>x.checksum===hash);const sameCreator=matches.length>0&&matches.every(x=>x.creatorId===input.creatorId);return result(hash,matches.length?(sameCreator?"MEDIUM":"HIGH"):"LOW",matches.length?(sameCreator?"พบไฟล์ซ้ำจากผู้สร้างเดิม":"พบไฟล์ซ้ำในคลัง KruPo"):"ไม่พบ SHA-256 ซ้ำ",matches.map(x=>({kind:"file_duplicate",reference:x.id,similarity:1,detail:`SHA-256 ตรงกัน: ${input.fileName}`})))}
 async checkWebSources(input:Parameters<CopyrightRiskProvider["checkWebSources"]>[0]){const canonical=(u:string)=>{const x=new URL(u);x.hash="";x.searchParams.sort();return x.toString()};const urls=input.urls.map(canonical),known=new Map((input.knownUrls??[]).map(x=>[canonical(x.url),x.id]));const found=urls.filter(u=>known.has(u));return result(await sha256(urls.join("\n")),found.length?"HIGH":"LOW",found.length?"พบ URL ซ้ำในคลัง KruPo":"ไม่พบ URL ซ้ำ",found.map(u=>({kind:"url_duplicate",reference:known.get(u),similarity:1,detail:u})),urls)}
}
